# Generated by Django 2.2.1 on 2019-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190617_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
