# Generated by Django 2.2.7 on 2019-11-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191112_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='Sınıf'),
        ),
    ]
