# Generated by Django 3.0.1 on 2020-03-27 15:35

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200327_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hikaye',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Açıklama'),
        ),
    ]
