# Generated by Django 3.0.1 on 2020-03-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200327_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='article',
            name='story_writer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yazar Adı'),
        ),
    ]
