# Generated by Django 3.0.1 on 2020-03-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200327_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(max_length=70, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='story_writer',
            field=models.CharField(max_length=50, verbose_name='Yazar Adı'),
        ),
    ]
