# Generated by Django 3.0.1 on 2020-03-27 20:51

import articles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200327_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(default='900x300.png', null=True, upload_to=articles.models.Article.get_file_path, verbose_name='Hikaye Kapağı Ekle'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hikaye',
            field=models.FileField(default='deneme.pdf', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
