# Generated by Django 2.1.7 on 2019-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtmek İstemiyorum', 'Belirtmek İstemiyorum')], default='Belirtmek İstemiyorum', max_length=2, null=True),
        ),
    ]
