# Generated by Django 2.1.7 on 2019-03-30 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190330_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birt_date',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
