# Generated by Django 2.1.7 on 2019-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190330_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtmek İstemiyorum', 'Belirtmek İstemiyorum')], default='Belirtmek İstemiyorum', max_length=21, null=True, verbose_name='Cinsiyet'),
        ),
    ]
